JOBORDER_WEB/Web_RIMP/Controllers/ReportsController.cs
using db.Data.JobOrder;
using db.Database;
using db.Global;
using db.Repository;
using db.Repository.APC;
using db.Repository.Employee;
using db.Repository.JobOrder;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using PagedList;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Web_RIMP.Models;

namespace Web_RIMP.Controllers
{
    public class ReportsController : Controller
    {
        #region Global
        RepositoryInitialization repository = new RepositoryInitialization();

        public ReportsController()
        {
            this.repository._jo = new JobOrder(new JOEntities());
            this.repository._employee = new Employee(new JOEntities());
            this.repository._jo_classification = new JobOrderClassification(new JOEntities());
            this.repository._apc = new Programmer(new JOEntities());
            this.repository._dreport = new DailyReport(new JOEntities());
            this.repository._monthly_report = new JobOrderReport(new JOEntities());
        }

        public ReportsController(IJoborder jo, IEmployee employee, IJobOrderClassification classification, IProgrammer apc)
        {
            this.repository._jo = jo;
            this.repository._employee = employee;
            this.repository._jo_classification = classification;
            this.repository._apc = apc;

        }

        #endregion

        #region Daily Report

        public ActionResult AllDailyReport(int? page)
        {
            var EmpID = Request.Cookies["EmpID"].Value.ToString();

            ViewBag.Apc = repository._apc.GetAPC()
                                    .Where(x => x.emp_id.Trim() != "g930192" && x.emp_id != "J0061")
                                    .OrderBy(x => x.emp_name)
                                    .Select(x => x.emp_name)
                                    .ToList();

            return View(GetReportByName(EmpID).ToPagedList(page ?? 1, 12));
        }

        public List<DailyReportModel> GetReportByName(string ApcID)
        {
            return repository._apc.GetAllReports()
                                  .Where(x => x.apc_id.Trim() == ApcID.Trim())
                                  .Select(x => new DailyReportModel
                                  {
                                      Date = x.date.ToString("yyyy-MM-dd"),
                                      TimeStart = x.time_start,
                                      TimeEnd = x.time_end,
                                      Mins = x.mins,
                                      Activity = x.work_description,
                                      CostCenter = x.cc_description,
                                      Company = x.company,
                                      JobNo = x.jobno
                                  })
                                  .OrderByDescending(x => x.Date).ThenBy(x => x.TimeStart)
                                  .ToList();
        }

        public ActionResult DailyReport()
        {
            if (Request.Cookies["Dept_ID"].Value.ToString() != "09")
                return RedirectToAction("NotAuthorized", "Home");

            var Apc = Request.Cookies["Fullname"].Value.Trim().ToString();
            var EmpID = Request.Cookies["EmpID"].Value.Trim().ToString();

            //var AllOngoingJO = repository._jo.GetAllJobOrder()
            //                                   .Join(repository._jo.GetAllJobOrderDetails(),
            //                                         e => e.details_id, c => c.details_id, (e, c) => new { e, c })
            //                                  .GroupBy(y => new
            //                                  {
            //                                      y.e.details_id,
            //                                      y.e.job_no,
            //                                      y.c.assignee,
            //                                      y.c.status_id
            //                                  })
            //                                  .Where(y => !String.IsNullOrEmpty(y.Key.assignee) && y.Key.assignee.Trim().Equals(Apc) && (y.Key.status_id != 6 && y.Key.status_id != 10))
            //                                  .Select(x => x.Key.job_no)
            //                                   .ToList();

            var ReportToday = repository._apc.GetAllReports()
                                             .Where(x => x.date.ToString("yyyy-MM-dd") == DateTime.Today.ToString("yyyy-MM-dd") &&
                                                         x.apc_id.Trim().Equals(EmpID.Trim()))
                                             .Select(x => new DailyReportModel
                                             {
                                                 ID = x.r_id,
                                                 TimeStart = x.time_start,
                                                 TimeEnd = x.time_end,
                                                 Mins = x.mins,
                                                 Activity = x.work_description,
                                                 CostCenter = x.cc_description,
                                                 Company = x.company
                                             })
                                             .OrderBy(x => x.TimeStart)
                                             .ToList();


            ViewBag.CostCenter = repository._jo.GetCCMeaning().ToList();
            ViewBag.AllOngoingJO = repository._monthly_report
                                                            .GetSharedJO(Apc)
                                                            .Select(x => x.job_no)
                                                            .ToList();

            return View(ReportToday);
        }
        public ActionResult ExportReportToExcel(string EmpID, string DateSent)
        {
            var collection = GetMyJobOrder(EmpID, Convert.ToDateTime(DateSent)).ToList();
            string filename = "APCDailyReport_" + EmpID.Trim() + "_" + DateSent;

            var Apc = repository._apc.GetAPC()
                                .Where(x => x.emp_id.Trim() == EmpID.Trim())
                                .Select(x => x.emp_name).FirstOrDefault();

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage(new FileInfo(filename + ".xlsx")))
            {
                ExcelWorksheet Sheet = package.Workbook.Worksheets.Add("Report");

                Sheet.Column(3).Width = 16;
                Sheet.Column(4).Width = 25;
                Sheet.Column(5).Width = 25;
                Sheet.Column(6).Width = 18;
                Sheet.Column(7).Width = 18;
                Sheet.Column(8).Width = 25;
                Sheet.Column(9).Width = 17;
                //Sheet.Column(6).Width = 25;
                //Sheet.Column(7).Width = 15;

                Color colFromHex = System.Drawing.ColorTranslator.FromHtml("#3E90FF");
                Color colValue = System.Drawing.ColorTranslator.FromHtml("#BFF0FB");

                //font size
                Sheet.Cells["C2:H2"].Style.Font.Size = 17;
                Sheet.Cells["C4:C4"].Style.Font.Size = 11;
                Sheet.Cells["C8:C8"].Style.Font.Size = 11;
                Sheet.Cells["F4:F4"].Style.Font.Size = 11;
                Sheet.Cells["C6:C6"].Style.Font.Size = 11;
                Sheet.Cells["D8:D8"].Style.Font.Size = 11;
                Sheet.Cells["G8:G8"].Style.Font.Size = 11;

                Sheet.Cells["D2:D2"].Style.Font.Bold = true;
                Sheet.Cells["C4:C4"].Style.Font.Bold = true;
                Sheet.Cells["C6:C6"].Style.Font.Bold = true;
                Sheet.Cells["F4:F4"].Style.Font.Bold = true;
                Sheet.Cells["C6:C6"].Style.Font.Bold = true;
                Sheet.Cells["D6:D6"].Style.Font.Bold = true;
                Sheet.Cells["G6:G6"].Style.Font.Bold = true;
                Sheet.Cells["D14:G14"].Style.Font.Bold = true;
                Sheet.Cells["F6:F6"].Style.Font.Bold = true;
                Sheet.Cells["H6:H6"].Style.Font.Bold = true;
                Sheet.Cells["I6:I6"].Style.Font.Bold = true;
                Sheet.Cells["C2:H2"].Style.Font.Bold = true;

                //bg color
                Sheet.Cells["C4:C4"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                Sheet.Cells["C4:C4"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                Sheet.Cells["C6:I6"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                Sheet.Cells["F4:F4"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                Sheet.Cells["C6:C6"].Style.Fill.PatternType = ExcelFillStyle.Solid;

                Sheet.Cells["C4:C4"].Style.Fill.BackgroundColor.SetColor(colFromHex);
                Sheet.Cells["C6:I6"].Style.Fill.BackgroundColor.SetColor(colFromHex);
                Sheet.Cells["F4:F4"].Style.Fill.BackgroundColor.SetColor(colFromHex);
                Sheet.Cells["C6:C6"].Style.Fill.BackgroundColor.SetColor(colFromHex);
                // Sheet.Cells["G6:G6"].Style.Fill.BackgroundColor.SetColor(colFromHex);

                //Header | APC Name
                Sheet.Cells["C2:H2"].Value = "DAILY STATUS REPORT - APC";
                Sheet.Cells["C4:C4"].Value = "NAME:";
                Sheet.Cells["D4:D4"].Value = Apc.Trim();
                Sheet.Cells["F4:F4"].Value = "DATE:";
                Sheet.Cells["G4:G4"].Value = DateSent;

                //Merge Text
                Sheet.Cells["C2:H2"].Merge = true;
                Sheet.Cells["C2:I2"].Style.VerticalAlignment = ExcelVerticalAlignment.Center;
                Sheet.Cells["C2:I2"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;

JOBORDER_WEB/Web_RIMP/Views/Reports/AllDailyReport.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Web_RIMP.Models.DailyReportModel>

@{
    ViewBag.Title = "AllDailyReport";
    Layout = "~/Views/Shared/Homepage_LayoutPage.cshtml";
    var EmpId = Request.Cookies["EmpID"].Value.ToString();

}

<link rel="stylesheet" href="~/Content/css/DailyReport.css">
<script src="~/Content/custom/JobOrders/DailyReport.js"></script>

<div class="page-header row no-gutters py-4" id="dvTitle">

    <div class="col-12">
        <div class="row">
            <div class="col-10">
                <h3 class="page-title" id="lblTitleHeader" style="font-size:25px;">All Daily Report</h3>
            </div>
        </div>
    </div>
</div>
<div class="card-body p-0 pb-3 text-center" id="tblverlay">
    <img src="~/Content/gif/loader7.gif" id="imgLoader" />
</div>

<div class="cards" id="dvBody">
    <div class="form-row">
        <div class="col">

        </div>
        <div class="col-2" style="margin-bottom:20px;margin-top:30px;">
            <div class="btn-group" role="group">
                <a href="@Url.Action("DailyReport","Reports")#rDailyReport" class="btn btn-danger" id="createBtn"><i class="fa fa-paint-brush"></i> Add Daily Report</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="form-row">
                <div class="col" id="dvDetails" style="margin-left: 20px;">
                    <h3>Cost Center</h3>
                    <canvas id="cc-reportchart" height="100"></canvas>
                </div>
                <div class="col-5">
                    <div class="table-responsive" style="height:450px;">
                        <div class="col-11" style="margin-left: 50px;">
                            <table class="table table-striped table-dark table-hover table-responsive-sm" id="tbl-apc-incharge">
                                <thead>
                                    <tr>
                                        <th style="width:70%;">In-Charge</th>
                                        <th>..</th>
                                    </tr>
                                </thead>
                                <tbody id="tb-apc-incharge" style="text-align: left;">
                                    @foreach (var apc in ViewBag.Apc)
                                    {

                                        <tr>
                                            <td style="width:70%;">@apc</td>
                                            <td></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-5">
            <div id="divHeader" class="custom-table">
                <p id="tblLabel">All Daily Report Entries</p>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top:10px;">
        <div class="col">
            <div class="col-md-12 col-sm-12">
                <div class="table-responsive">
                    <table class="table table-striped table-dark table-hover table-responsive-sm" id="tbl-reports">
                        <thead class="thead-dark">
                            <tr>
                                <th style="width:200px;">Date</th>
                                <th style="width:150px;">Start</th>
                                <th style="width:150px;">End</th>
                                <th style="width:150px;">Mins</th>
                                <th style="width:700px;">Activity</th>
                                <th style="width:200px;">Cost Center</th>
                                <th style="width:150px;">Company</th>
                                <th style="width:25px;"></th>
                            </tr>
                        </thead>
                        <tbody id="tb-reports">
                            @{
                                var PrevDate = "";
                            }

                            @foreach (var report in Model)
                            {
                                var Date = report.Date;

                                <tr>
                                    <td style="width:200px;">@Html.DisplayFor(modelItem => report.Date)</td>
                                    <td style="width:150px;">@Html.DisplayFor(modelItem => report.TimeStart)</td>
                                    <td style="width:150px;">@Html.DisplayFor(modelItem => report.TimeEnd)</td>
                                    <td style="width:150px;">@Html.DisplayFor(modelItem => report.Mins)</td>
                                    <td style="width:700px;">@Html.DisplayFor(modelItem => report.Activity)</td>
                                    <td style="width:200px;">@Html.DisplayFor(modelItem => report.CostCenter)</td>
                                    <td style="width:150px;text-align:center;">@Html.DisplayFor(modelItem => report.Company)</td>
                                    <td style="width:25px;">

                                        @if (PrevDate != Date)
                                        {
                                            <button class="btn btn-info" onclick="resendEmail('@EmpId','@Date')" data-bs-toggle="tooltip" data-bs-placement="top" title="Resend Email"><i class="fa fa-send"></i></button>
                                        }
                                    </td>
                                </tr>
                                PrevDate = report.Date;

                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <!-- end of wrap -->
            <!-- end of container -->
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="col-2" id="swPagerID" style="color:white;">
                Showing @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                out of @Model.PageCount pages
            </div>
        </div>
        <div class="col">
            @Html.PagedListPager(Model, page => Url.Action("AllDailyReport", new { page }))
        </div>
    </div>
</div>
<br />


<div class="modal fade md-confirmation" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog  modal-dialog-scrollable modal-dialog-centered modal-sm">
        <!-- Modal Content: begins -->
        <div class=" modal-content">
            <!-- Modal Body -->
            <div class="modal-body" id="dvDetails">
                <div class="body-message">
                    <div id="divHeader" class="custom-table">
                        <p id="tblLabel">Send Email</p>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div style="display:none;">
                                <label id="lbl-empid"></label>
                                <label id="lbl-datesent"></label>
                            </div>
                            <h4> <i class="fa fa-send-o"></i> Re-send report now?</h4>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div class="col-5">

                        </div>
                        <div class="col">
                            <button type="button" class="btn btn-primary" onclick="sendEmail()"><i class="fa fa-check-square-o"></i> Yes</button>
                            <button type="button" class="btn btn-dark" data-dismiss="modal"><i class="fa fa-times-rectangle"></i> No</button>
                        </div>
                    </div>

                </div>
                <!-- Modal Content: ends -->
            </div>
            <!-- Modal Footer -->
        </div>
    </div>
</div>

JOBORDER_WEB/Web_RIMP/Views/Reports/JOMonthlyReport.cshtml
@{
    ViewBag.Title = "JOMonthlyReport";
    Layout = "~/Views/Shared/Homepage_LayoutPage.cshtml";


    DateTime date = DateTime.Today;

    var firstDayOfMonth = new DateTime(date.Year, date.Month, 1).AddMonths(-1);
    var lastDayOfMonth = firstDayOfMonth.AddMonths(1).AddDays(-1);

}

<script src="~/Content/js/jspdf.debug.js"></script>
<script src="~/Content/js/chartjs/Chart.js"></script>
<script src="~/Content/custom/JobOrders/MonthlyReport.js"></script>
<div class="page-header row no-gutters py-4" id="dvTitle">
    <div class="col-12">
        <div class="row">
            <div class="col">
                <h3 class="page-title" id="lblTitleHeader" style="font-size:25px;">Job Order Monthly Report</h3>
            </div>
        </div>
    </div>
</div>
<hr>

<div class="cards">
    <div id="dvBody">
        <div class="row">
            <div class="col-6">
                <div class="row" style="margin-top:10px;">
                    <div class="col-7">
                        <div class="input-group">
                            <input type="text" id="txt-datestart" class="form-control" value="@firstDayOfMonth.ToString("yyyy-MM-dd")" placeholder="Start Date">
                            <input type="text" id="txt-dateend" class="form-control" value="@lastDayOfMonth.ToString("yyyy-MM-dd")" placeholder="End Date">
                            <div class="btn-group">
                                <button type="button" class="btn btn-dark" onclick="searchMonthReport()">
                                    <i class="fa fa-search"></i> Find
                                </button>
                            </div>                           
                        </div>
                    </div>
                </div>
            </div>
            <div class="col" style="margin-top:10px;">
                <button type="button" class="btn btn-success" onclick="exportToExcel()" style="float:right;"><i class="fa fa-file-excel-o"></i> Export To Excel</button>

            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-6" id="dvDetails" style="margin-left: 20px;">
                <h3>Cost Center Monthly Graph</h3>
                <canvas id="cc-chart" height="180"></canvas>
            </div>
            <div class="col-5" id="dvDetails" style="margin-left: 20px;">
                <h3>Cost Center Percentage</h3>
                <canvas id="cc-percentage" height="180"></canvas>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="table-responsive">
                <div class="col-11" style="margin-left: 50px;">
                    <table class="table table-striped table-dark table-hover table-responsive-lg" id="tbl-jo-details">
                        <thead>
                            <tr id="tblTr">
                              <th>JO #</th>
                              <th>Department</th>
                              <th>Cost Center</th>
                              <th>In-Charge</th>
                              <th style="width:120px;">Actual Time</th>
                              <th style="width:80px;"></th>
                            </tr>
                        </thead>
                        <tbody id="tb-jo-details" style="text-align:right;">
                            <tr>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>