JOBORDER_WEB/Web_RIMP/Controllers/JobOrdersController.cs
using DataMatrix.net;
using db.Data.Dashboard;
using db.Data.JobOrder;
using db.Database;
using db.Global;
using db.Repository.APC;
using db.Repository.Applications;
using db.Repository.Employee;
using db.Repository.GanttChart;
using db.Repository.JobOrder;
using db.Repository.Priority;
using db.Repository.Status;
using OfficeOpenXml;
using OfficeOpenXml.Drawing.Chart;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Web_RIMP.Models;

namespace Web_RIMP.Controllers
{
    [Authorize]
    public class JobOrdersController : Controller
    {
        #region Global Initialization

        RepositoryInitialization repository = new RepositoryInitialization();


        public JobOrdersController()
        {
            this.repository._jo_classification = new JobOrderClassification(new JOEntities());
            this.repository._employee = new Employee(new JOEntities());
            this.repository._jo_priority = new Priority(new JOEntities());
            this.repository._jo = new JobOrder(new JOEntities());
            this.repository._jostatus = new Status(new JOEntities());
            this.repository._apc = new Programmer(new JOEntities());
            this.repository._app = new Applications(new JOEntities());
            this.repository._gant_chart = new GanttChart(new JOEntities());
            this.repository._monthly_report = new JobOrderReport(new JOEntities());
            this.repository._dashboard = new Dashboard(new JOEntities());
        }

        public JobOrdersController(JobOrderClassification jo_classification, Employee emp,
                                   Priority priority, JobOrder jo, Status status, Programmer apc,
                                   Applications app, GanttChart gant_chart, JobOrderReport report,
                                   Dashboard dashboard)
        {
            this.repository._jo_classification = jo_classification;
            this.repository._employee = emp;
            this.repository._jo_priority = priority;
            this.repository._jo = jo;
            this.repository._jostatus = status;
            this.repository._apc = apc;
            this.repository._app = app;
            this.repository._gant_chart = gant_chart;
            this.repository._monthly_report = report;
            this.repository._dashboard = dashboard;
        }
        #endregion

        #region Non KPI JO

        #region All Job Orders Tab
        public ActionResult AllJobOrders()
        {
            return View();
        }

        public ActionResult ExportToExcelJO(string DateFrom, string DateTo)
        {
            string filename = "Joborder-Report-" + DateTime.Today.ToShortDateString() + ".xlsx";

            var collection = repository._jo.ExportJOToExcel(
                                        Convert.ToDateTime(Convert.ToDateTime(DateFrom).ToString("yyyy-MM-dd")),
                                        Convert.ToDateTime(Convert.ToDateTime(DateTo).ToString("yyyy-MM-dd")),
                                        1)
                                        .ToList();

            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
            using (var package = new ExcelPackage(new FileInfo("MyWorkbook.xlsx")))
            {
                ExcelWorksheet Sheet1 = package.Workbook.Worksheets.Add("JO Summary");
                ExcelWorksheet Sheet2 = package.Workbook.Worksheets.Add("JO Details");

                Color colFromHex = System.Drawing.ColorTranslator.FromHtml("#4d5076");
                Color colValue = System.Drawing.ColorTranslator.FromHtml("#759dd2");

                //Header Title
                Sheet2.Cells["A1:I1"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                Sheet2.Cells["A1:I1"].Style.Fill.BackgroundColor.SetColor(colFromHex);
                Sheet2.Cells["A1:I1"].Style.Font.Color.SetColor(Color.White);
                Sheet2.Cells["A1:I1"].Style.Font.Size = 20;
                Sheet2.Cells["D1:D1"].Value = "APC Job Orders Monthly Report " + Convert.ToDateTime(DateFrom).ToString("yyyy-MM");
                //END

                //Header Name Style / Color
                Sheet2.Cells["A2:I2"].Style.Fill.PatternType = ExcelFillStyle.Solid;
                Sheet2.Cells["A2:I2"].Style.Fill.BackgroundColor.SetColor(colValue);
                Sheet2.Cells["A2:I2"].Style.Font.Color.SetColor(Color.White);
                Sheet2.Cells["A2:I2"].Style.Font.Size = 15;

                Sheet2.Cells["A2"].Value = "Requesting Department";
                Sheet2.Cells["B2"].Value = "Cost Center";
                Sheet2.Cells["C2"].Value = "Job Order No.";
                Sheet2.Cells["D2"].Value = "Details";
                Sheet2.Cells["E2"].Value = "APC In-Charge";
                Sheet2.Cells["F2"].Value = "Job Order Status";
                Sheet2.Cells["G2"].Value = "Date Started";
                Sheet2.Cells["H2"].Value = "Date Ended";
                Sheet2.Cells["I2"].Value = "Minutes";
                //END

                //Add excel cell a value
                int row = 3;

                foreach (var item in collection)
                {
                    Sheet2.Cells[string.Format("A{0}", row)].Value = item.department;
                    Sheet2.Cells[string.Format("B{0}", row)].Value = item.costcenter;
                    Sheet2.Cells[string.Format("C{0}", row)].Value = item.jo_no;
                    Sheet2.Cells[string.Format("D{0}", row)].Value = item.details;
                    Sheet2.Cells[string.Format("E{0}", row)].Value = item.apc;
                    Sheet2.Cells[string.Format("F{0}", row)].Value = item.jo_status;
                    Sheet2.Cells[string.Format("G{0}", row)].Value = item.date_started;
                    Sheet2.Cells[string.Format("H{0}", row)].Value = item.date_ended;
                    Sheet2.Cells[string.Format("I{0}", row)].Value = item.hrs_mins;

                    row++;
                }

                var Graph = repository._monthly_report.GetCostCenterGraph(Convert.ToDateTime(DateFrom), Convert.ToDateTime(DateTo)).ToList();

                int? Totalminutes = 0;
                DataTable tbl = new DataTable();

                tbl.Columns.Add("Cost Center", typeof(string));
                tbl.Columns.Add("Minutes", typeof(int));
                tbl.Columns.Add("Percentage", typeof(double));

                foreach (var g in Graph)
                {

                    var total = g.total;
                    Totalminutes = g.overalltotal;

                    var tmppercentage = (Convert.ToDouble(total) / Totalminutes) * 100;
                    double percentage = Math.Round(Convert.ToDouble(tmppercentage), 1);

                    tbl.Rows.Add(g.cc_description, g.total, percentage);
                }

                Sheet1.Cells["B15"].Style.Font.Size = 15;
                Sheet1.Cells["B15"].Value = "Total Minutes: " + Totalminutes;

                //Datable
                Sheet1.Cells[1, 1].LoadFromDataTable(tbl, true, OfficeOpenXml.Table.TableStyles.Medium6);

                //Tota Cost Center BAR Chart
                ExcelChart bargraph = Sheet1.Drawings.AddChart("chart", eChartType.ColumnClustered);
                bargraph.Title.Text = "JO Cost Center Chart";
                bargraph.XAxis.Title.Text = "Cost Center"; //give label to x-axis of chart  
                bargraph.XAxis.Title.Font.Size = 10;

                bargraph.SetPosition(3, 3, 3, 4);
                bargraph.SetSize(800, 400);

                //Percentage pie graph
                ExcelChart piegraph = Sheet1.Drawings.AddChart("piechart", eChartType.Pie);
                piegraph.Title.Text = "Cost Center Percenatage";

                piegraph.SetPosition(24, 3, 3, 25);
                piegraph.SetSize(800, 400);

                var ser1 = bargraph.Series.Add(Sheet1.Cells["B2:B14"], Sheet1.Cells["A2:A14"]);
                var ser2 = piegraph.Series.Add(Sheet1.Cells["C2:C14"], Sheet1.Cells["A2:A14"]);

                ser1.Header = "Cost Center";
                ser2.Header = "Percentage";

                Sheet1.Cells["A:AZ"].AutoFitColumns();
                Sheet2.Cells["A:AZ"].AutoFitColumns();

                Sheet1.Cells[Sheet1.Dimension.Address].Style.Border.Top.Style = ExcelBorderStyle.Thin;
                Sheet1.Cells[Sheet1.Dimension.Address].Style.Border.Right.Style = ExcelBorderStyle.Thin;

                Sheet2.Cells[Sheet2.Dimension.Address].Style.Border.Top.Style = ExcelBorderStyle.Thin;
                Sheet2.Cells[Sheet2.Dimension.Address].Style.Border.Right.Style = ExcelBorderStyle.Thin;
                Response.Clear();
                Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
                Response.AddHeader("content-disposition", "attachment: filename=" + filename);
                Response.BinaryWrite(package.GetAsByteArray());
                Response.End();
                //-- END --
            }
            return View();

        }

        #endregion

        #region New Job Order Tab    
        public ActionResult CreateJobOrder()
        {
            List<CreateJobOrderModel> NewJobOrder = new List<CreateJobOrderModel>();

            try
            {
                //Job Order cards values
                var JOCounts = repository._jo_classification.SPOnGoingJO().FirstOrDefault();

                //All unassigned JO
                NewJobOrder = repository._jo_classification.SPJoUnassignedList()
                                                            .Where(x => x.status == "Created")
                                                           .Select(x => new CreateJobOrderModel()
                                                           {

JOBORDER_WEB/Web_RIMP/Views/JobOrders/AddSurvey.cshtml
@{
    ViewBag.Title = "AddSurvey";
    Layout = "~/Views/Shared/Homepage_LayoutPage.cshtml";
}

JOBORDER_WEB/Web_RIMP/Views/JobOrders/AllHardwareJO.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Web_RIMP.Models.AllHardwareJOModel>


<div class="row">
    <div class="col-12" id="dvBody">
        <div id="divHeader" class="custom-table">
            <p id="tblLabel">List Of All Hardware Job Order</p>
        </div>
        <div id="searchDiv">
            <div class="row">
                <div class="col">
                    <div class="input-group" id="txtSearch">
                        <input type="text" class="form-control" placeholder="Search applications/Programmer" id="txt-hw-search">
                        <div class="input-group-append">
                            <button class="btn btn-dark" type="button" id="btn-hw-search" onclick="joSearch('hw')">
                                <i class="fa fa-search"></i>
                            </button>
                            <button class="btn btn-info" type="button" onclick="reloadPage()">
                                <i class="fa fa-refresh"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="searchTbl">

        </div>
        <div class="table-responsive">
            <table class="table table-striped table-dark table-hover table-responsive" id="tbl-hw" style="text-align:center;">
                <thead class="thead-dark">
                    <tr id="tblTr">
                        <th style="width:17%">Job Order #</th>
                        <th>Type</th>
                        <th style="width:25%">Details</th>
                        <th>Status</th>
                        <th style="width:7%;">Standard Time</th>
                        <th>Assignee</th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                <tbody id="tb-hw">
                    @foreach (var model in Model)
                    {
                        var jo = model.JoNumber;
                        <tr>
                            <td style="width:17%">@Html.DisplayFor(modelItem => model.JoNumber)</td>
                            <td>@Html.DisplayFor(modelItem => model.Type)</td>
                            <td style="width:25%">@Html.DisplayFor(modelItem => model.Details)</td>
                            <td>@Html.DisplayFor(modelItem => model.Status)</td>
                            <td style="width:7%;">@Html.DisplayFor(modelItem => model.StandardTime)</td>
                            <td>@Html.DisplayFor(modelItem => model.Assignee)</td>
                            <td style="width:10%;">
                                <a href="@Url.Action("JobOrderDetails","JobOrders",new { JoNumber = jo})#AllJo" class="btn btn-outline-warning" id="createBtn" style="float:left;">
                                    <i class="fa fa-pencil-square" style="font-size:18px;"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-2" id="hwPagerID" style="color:white;">
                Showing @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                out of @Model.PageCount pages
            </div>
            <div id="hwID" class="col-10" style="margin-top:-25px;">

                @Html.PagedListPager((IPagedList)Model, page => Url.Action("AllHardwareJO", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                 new AjaxOptions()
                 {
                     HttpMethod = "GET",
                     UpdateTargetId = "hwID",
                     OnBegin = "displayLoader",
                 }))
            </div>
        </div>
    </div>
</div>

JOBORDER_WEB/Web_RIMP/Views/JobOrders/AllJobOrders.cshtml
@{
    ViewBag.Title = "AllJobOrders";
    Layout = "~/Views/Shared/Homepage_LayoutPage.cshtml";
}
<script src="~/Content/custom/JobOrders/AllJobOrder.js"></script>

<div class="page-header row no-gutters py-4" id="dvTitle">
    <div class="col-12">
        <div class="row">
            <div class="col">
                <div class="btn-group" role="group" id="topNav">
                    <button class="btn btn-danger" onclick="gotoAllHardware()" id="jo-type-hw" style="border-left:solid;color:white;">
                        <i class="fa fa-cog fa-2x"></i>
                        Hardware
                    </button>
                    <button class="btn btn-dark" onclick="gotoAllSoftware()" id="jo-type-sw" style="border-left:solid;">
                        <i class="fa fa-laptop fa-2x"></i> Software
                    </button>

                </div>
            </div>
            <div class="col">
                <h3 class="page-title" id="lblTitleHeader" style="font-size:25px;float:right;margin-right:10px;">All Job Orders</h3>
            </div>
        </div>
    </div>
</div>

<div class="card-body p-0 pb-3 text-center" id="tblverlay">
    <img src="~/Content/gif/loader7.gif" id="imgLoader" />
</div>

<div id="dvContainer">
    <div class="row">
        <div class="col-7">

        </div>
        @*<div class="col" style="float:right;">
            <div class="input-group">
                <input type="text" id="txt-excel-start" class="form-control" placeholder="Start Date">
                <input type="text" id="txt-excel-end" class="form-control" placeholder="End Date">
                <button class="btn btn-success" onclick="exportToExcel()">
                    <i class="fa fa-file-excel-o"></i> Export To Excel
                </button>
            </div>
        </div>*@
    </div>
    <div id="hwID" class="w3 w3-animate-right">
        @Html.Action("AllHardwareJO")
    </div>
    <div id="swID" style="display:none;" class="w3 w3-animate-right">
        @Html.Action("AllSoftwareJO")
    </div>

</div>

JOBORDER_WEB/Web_RIMP/Views/JobOrders/AllSoftwareJO.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Web_RIMP.Models.AllSoftwareJOModel>

@{
    var progress = 0;
}


<div class="row">
    <div class="col-12" id="dvBody">
        <div id="divHeader" class="custom-table">
            <p id="tblLabel">On Going Development</p>
        </div>
        <div id="searchDiv">
            <div class="input-group" id="txtSearch">
                <input type="text" class="form-control" placeholder="Search applications/Programmer" id="txt-sw-search">
                <div class="input-group-append">
                    <button class="btn btn-dark" type="button" onclick="joSearch('sw')">
                        <i class="fa fa-search"></i>
                    </button>
                    <button class="btn btn-info" type="button" onclick="reloadPage()">
                        <i class="fa fa-refresh"></i>
                    </button>
                </div>
            </div>
        </div>
        <div id="searchTbl">

        </div>
        <div class="table-responsive">
            <table class="table table-striped table-dark table-hover table-responsive-lg table-bordered" id="tbl-sw" style="text-align:center;">
                <thead class="thead-dark">
                    <tr id="tblTr">

                        <th style="width:10%;">Code Number</th>
                        <th>Application</th>
                        <th>Status</th>
                        <th>Progress</th>
                        <th>Assignee</th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                <tbody id="tb-sw">
                    @foreach (var model in Model)
                    {
                        var jo = model.JoNumber;
                        var width = "";
                        var progressColor = "";
                        var status = model.Status;
                        <tr>
                            <td style="width:10%;">@Html.DisplayFor(modelItem => model.CodeNumber)</td>
                            <td>@Html.DisplayFor(modelItem => model.AppName)</td>
                            <td>@Html.DisplayFor(modelItem => model.Status)</td>
                            <td>
                                @switch (status)
                                {

                                    case "For Approval":
                                        progress = 5;
                                        width = progress + "%";
                                        progressColor = "progress-bar progress-bar-striped";
                                        break;
                                    case "Requirements":
                                        progress = 20;
                                        width = progress + "%";
                                        progressColor = "progress-bar progress-bar-striped bg-success";
                                        break;
                                    case "Development":
                                        progress = 40;
                                        width = progress + "%";
                                        progressColor = "progress-bar progress-bar-striped bg-info";
                                        break;
                                    case "Testing":
                                        progress = 60;
                                        width = progress + "%";
                                        progressColor = "progress-bar progress-bar-striped bg-warning";
                                        break;
                                    case "Debugging":
                                        progress = 80;
                                        width = progress + "%";
                                        progressColor = "progress-bar progress-bar-striped bg-danger";
                                        break;
                                    case "Orientation":
                                        progress = 100;
                                        width = progress + "%";
                                        progressColor = "progress-bar bg-success";
                                        break;
                                }
                                <div class="progress">

                                    <div class="@progressColor" role="progressbar" style="width: @width" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100">
                                        @progress%
                                    </div>
                                </div>
                            </td>
                            <td>@Html.DisplayFor(modelItem => model.Assignee)</td>
                            <td style="width:10%;">
                                <a href="@Url.Action("JobOrderDetails","JobOrders",new { JoNumber = jo})#AllJo" class="btn btn-outline-warning" id="createBtn" style="float:left;">
                                    <i class="fa fa-pencil-square" style="font-size:18px;"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-2" id="swPagerID" style="color:white;">
                Showing @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                out of @Model.PageCount pages
            </div>
            <div id="swID" class="col-10" style="margin-top:-25px;">

                @Html.PagedListPager((IPagedList)Model, page => Url.Action("AllSoftwareJO", new { page }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(
                 new AjaxOptions()
                 {
                     HttpMethod = "GET",
                     UpdateTargetId = "swID",
                     OnBegin = "displayLoader",
                 }))
            </div>
        </div>
    </div>
</div>

JOBORDER_WEB/Web_RIMP/Views/JobOrders/JOApproval.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SurveySubmission</title>

    @* --------- C S S --------------*@
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link rel="stylesheet" href="~/Content/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/jquery-ui.css">
    @* <link rel="stylesheet" href="~/Content/js/qTip/jquery.qtip.css">*@

    @*--------- E N D ---------------*@


    @*--------J a v a s c r i p t ---*@
    <script src="~/Content/js/jquery-3.4.1.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/bootstrap.js"></script>
    <script src="~/Content/js/jquery.validate.min.js"></script>
    <script src="~/Content/js/modernizr-2.8.3.js"></script>
    <script src="~/Content/js/jquery-ui.js"></script>
    <script src="~/Content/js/jquery.unobtrusive-ajax.js"></script>

    <style>
            .good-review-score {
                background-color: #66CC33;
                color: white;
                text-align: center;
                padding: 10px;
                margin-right: 5px
                /*width: 50px;
        height: 30px;
        line-height: 30px*/
            }
    </style>
</head>
<body>
    <div class="row" style="margin-top:100px;">
        <div class="col-4">

        </div>
        <div class="col-8">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <h1 class="card-text good-review-score float-left"><i class="fa fa-star"></i></h1>
                                <h4 class="card-title">Job Order Approval.</h4>
                                <p class="card-text">Successfully forwarded the JO to APC department.</p>
                            </div>
                            <div class="card-footer">
                                <p class="card-text text-right"><a href="http://kpsweb2:1001">Go To Job Order</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

JOBORDER_WEB/Web_RIMP/Views/JobOrders/OnGoingJO.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.IPagedList<Web_RIMP.Models.AllHardwareJOModel>

@{
    var UnassignedCount = 1;
    var AssignedCount = 1;
}

<div class="row">
    <div class="col-4" id="dvBody">
        <div id="divHeader" class="custom-table">
            <p id="tblLabel">All Unassigned JO</p>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-dark table-hover table-responsive" id="tbl-unassigned-jo" style="text-align:center;">
                <thead class="thead-dark">
                    <tr id="tblTr">
                        <th style="width:2%"></th>
                        <th>Type</th>
                        <th style="width:25%">Details</th>
                        <th>Date Filed</th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                <tbody id="tb-hw">
                    @foreach (var model in Model)
                    {
                        var jo = model.JoNumber;
                        var assignee = model.Assignee;
                        if (assignee == "Unassigned")
                        {

                            <tr>
                                <td  style="width:2%">[@UnassignedCount]</td>
                                <td>@Html.DisplayFor(modelItem => model.Type)</td>
                                <td style="width:25%">@Html.DisplayFor(modelItem => model.Details)</td>
                                <td>@Html.DisplayFor(modelItem => model.Datefiled)</td>
                                <td style="width:10%;">
                                    <a href="@Url.Action("JobOrderDetails", "JobOrders", new { JoNumber = jo })#AllJo" class="btn btn-outline-warning" id="createBtn" style="float:left;">
                                        <i class="fa fa-pencil-square" style="font-size:18px;"></i>
                                    </a>
                                </td>
                            </tr>
                            UnassignedCount++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-7" id="dvBody" style="margin-left:30px;">
        <div id="divHeader" class="custom-table">
            <p id="tblLabel">All Assigned JO</p>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-dark table-hover table-responsive" id="tbl-assigned-jo" style="text-align:center;">
                <thead class="thead-dark">
                    <tr id="tblTr">
                        <th style="width:2%"></th>
                        <th>Type</th>
                        <th style="width:25%">Details</th>
                        <th>Date Filed</th>
                        <th>Date Target</th>
                        <th>Assignee</th>
                        <th style="width:10%;"></th>
                    </tr>
                </thead>
                <tbody id="tb-hw">
                    @foreach (var model in Model)
                    {
                        var jo = model.JoNumber;
                        var assignee = model.Assignee;

                        if (assignee != "Unassigned")
                        {

                            <tr>
                                <th style="width:2%">[@AssignedCount]</th>
                                <td>@Html.DisplayFor(modelItem => model.Type)</td>
                                <td style="width:25%">@Html.DisplayFor(modelItem => model.Details)</td>
                                <td>@Html.DisplayFor(modelItem => model.Datefiled)</td>
                                <td>@Html.DisplayFor(modelItem => model.DateTarget)</td>
                                <td>@Html.DisplayFor(modelItem => model.Assignee)</td>
                                <td style="width:10%;">
                                    <a href="@Url.Action("JobOrderDetails", "JobOrders", new { JoNumber = jo })#AllJo" class="btn btn-outline-warning" id="createBtn" style="float:left;">
                                        <i class="fa fa-pencil-square" style="font-size:18px;"></i>
                                    </a>
                                </td>
                            </tr>
                            AssignedCount++;
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

JOBORDER_WEB/Web_RIMP/Views/JobOrders/SurveySubmission.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SurveySubmission</title>

    @* --------- C S S --------------*@
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link rel="stylesheet" href="~/Content/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/css/jquery-ui.css">
    @* <link rel="stylesheet" href="~/Content/js/qTip/jquery.qtip.css">*@

    @*--------- E N D ---------------*@


    @*--------J a v a s c r i p t ---*@
    <script src="~/Content/js/jquery-3.4.1.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/bootstrap.js"></script>
    <script src="~/Content/js/jquery.validate.min.js"></script>
    <script src="~/Content/js/modernizr-2.8.3.js"></script>
    <script src="~/Content/js/jquery-ui.js"></script>
    <script src="~/Content/js/jquery.unobtrusive-ajax.js"></script>

    <style>
        .good-review-score {
            background-color: #66CC33;
            color: white;
            text-align: center;
            padding: 10px;
            margin-right: 5px
            /*width: 50px;
    height: 30px; 
    line-height: 30px*/
        }
    </style>
</head>
<body>
    <div class="row" style="margin-top:100px;">
        <div class="col-4">
            
        </div>
        <div class="col-8">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-block">
                                <h1 class="card-text good-review-score float-left"><i class="fa fa-star"></i></h1>
                                <h4 class="card-title">Job Order Successfully Closed.</h4>
                                <p class="card-text">You succesfully confirmed and closed this JO,thank you very much for taking the time to send us your feedback.</p>
                            </div>
                            <div class="card-footer">
                                <p class="card-text text-right"><a href="http://kpsweb2:1001">Go To Job Order</a></p>
                            </div>
                        </div>                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>